# Generated by Django 4.2.26 on 2025-11-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("about", models.TextField()),
                ("used_for", models.TextField()),
                ("image", models.ImageField(upload_to="plants/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("indoor", "Indoor"),
                            ("outdoor", "Outdoor"),
                            ("succulent", "Succulent"),
                            ("herb", "Herb"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_edible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
